Rename the package to 'su2'
Trying to fix
https://github.com/su2code/Docker-Builds/runs/6294621678?check_suite_focus=true :

error: failed to solve: ghcr.io/su2code/su2code/build-su2:220504-1749: failed to copy: httpReadSeeker: failed open: unexpected status code https://ghcr.io/v2/su2code/su2code/build-su2/blobs/sha256:acfa7418dcbda0c50041afdba1c84fcf7ba58ebc33f5750f2a67fc159f656d53: 403 Forbidden - Server message: denied: permission_denied: read_package
Error: buildx failed with: error: failed to solve: ghcr.io/su2code/su2code/build-su2:220504-1749: failed to copy: httpReadSeeker: failed open: unexpected status code https://ghcr.io/v2/su2code/su2code/build-su2/blobs/sha256:acfa7418dcbda0c50041afdba1c84fcf7ba58ebc33f5750f2a67fc159f656d53: 403 Forbidden - Server message: denied: permission_denied: read_package

At the moment there is a package at
https://github.com/su2code/SU2/pkgs/container/SU2%2Fbuild-su2 that can
be pulled with:

    docker pull ghcr.io/su2code/su2/build-su2:latest

Maybe the failed 'read_package' is because of the mismatch in the names:
'su2code' vs. 'su2'

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>